export { h } from "./h"
export { renderSlots } from "./helpers/renderSlots"
export { createTextVNode } from "./vnode"
export { getCurrentInstance } from "./components"
export { provide, inject } from "./apiInject"
export { createRenderer } from "./renderer"
export { nextTick } from "./scheduler"